version: '3'

services:
    nginx-service:
        image: nginx:stable-alpine
        container_name: nginx-container
        ports:
            - "8080:80"
        volumes:
            # project dir : dir in docker
            - ./app:/var/www/project
            - ./nginx/templates:/etc/nginx/templates
        environment:
            - NGINX_HOST=localhost
            - NGINX_PORT=80
        depends_on:
            - php-service
            - mysql-service

    php-service:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        container_name: php-container
        ports:
            - "9000:9000"
        volumes:
            - ./app:/var/www/project

    mysql-service:
        image: mariadb:10.5.5
        container_name: database-container
        ports:
            - "3306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        restart: always
        environment:
            MYSQL_DATABASE: app
            MYSQL_ROOT_PASSWORD: toor
            MYSQL_USERNAME: root
            MYSQL_PASSWORD: toor